### ISSUE TITLE
URLs are not handled properly

### ISSUE THREAD

**Issue by maxlapides** [code-and-send/detergent#11]
For example:

```
detergent('https://detergent.io')
```

returns:

```
https://detergent. io
```

Other than this issue, absolutely loving this library! Great work!

**Comment by revelt** [comment]
Good idea!

**Comment by revelt** [comment]
@maxlapides please review the library's functionality around the URL's when you get a chance.

**Comment by maxlapides** [comment]
@revelt awesome, thanks for jumping on this so fast! the case i mentioned above is definitely covered now, but what about something like this?

```
detergent('check out my new website at detergent.io, it's awesome')
```

what do you think about making this automatic-space-after-period thing an option that i can disable?

**Comment by revelt** [comment]
@maxlapides well, the purpose of Detergent is to clean text for pasting into HTML. You would still have to manually wrap and style the `<a>` tag, plus commercial emails never feature URL's, they only link somewhere:

```html
Text-before <a href="xxx" target="_blank" style="color: and-so-on and-so-on">label-text</a> text-after.
```

So, normally, I would run Detergent on the whole text coming from your Brief (like everything in the above example), including links and whatnot and paste into HTML template. Result will be without links, but encoded and cleaned. Then you would manually I'd wrap `linked-text` with `a` tag to look like above.

If you're using a **build system**, workflow would be this: 1. separate all content into JSON files, one folder per-email build, content JSON and template inside. 2. build templates on your preferred templating language, reading-in the content from JSON. 3. when setting up template, pass all text fields through Detergent (via custom [filter](https://mozilla.github.io/nunjucks/templating.html#filters) piping through Detergent, for example). Your JSON will contain URL's too, you simply wouldn't apply Detergent filter on them. Now, you might have cases where there's mingled text, like footer copy. In those cases, hardcode pre-Detergent-encoded HTML straight into the template partial, then call it where necessary.

This is off-topic, but I would strongly recommend to check out Nunjucks + Gulp setup.
I completely agree with [this](https://medium.com/@andy.neale/nunjucks-a-javascript-template-engine-7731d23eb8cc#.22xnittx9) article discarding Handlebars. Nunjucks will lessen your reliance on JS. Also, I never use automated inlining because you can insert attributes with snippets anyway. However, when you rely on inlining, you never really control the bottom level of your code.

Now with regards of adding `automatic-space-after-period` function, I'd be against it because of two reasons: 1) one more option will double the total combinations amount of unit tests (from 1024, ten options to 2048, eleven options) per complete feature. This means average test will take around <10 minutes (currently it's <5 minutes). 2) URL's are never meant to be mingled among the copy, they are always separated on template level, be it manual build or automated.

Do you see my point?

**Comment by maxlapides** [comment]
I do see what you're saying, but I think your assumption that "URL's are never meant to be mingled among the copy" isn't correct. In the example above, I want to mention a website by domain name, but I don't want to necessarily wrap it in a link. This is an unusual case for sure, but I see that as more of a problem than the case where a space after a period is missing. And generally it's best to not make design decisions because of testing.

(Off-topic, I bring all of this up because I'm working on a general purpose email compiler: https://github.com/maxlapides/dovetailer. I am using Handlebars as my template system right now, but I'll definitely check out Nunjucks, I'm not wed to Handlebars are anything.)

**Comment by revelt** [comment]
If you don't wrap url with a link, how then do you style it (colour, underline etc) and set the `target="_blank"`?

**Comment by maxlapides** [comment]
In this case, I don't want it to be a link or styled in any special way. I just wanna say something like "I just bought some cool new domain names: mywebsite.com and myotherwebsite.net"

**Comment by maxlapides** [comment]
Also consider some other similar cases:

```
my email address is myemail@mydomain.com
in your code, run myInstance.func()
```

**Comment by revelt** [comment]
Detergent's aim is to be smart text encoding tool, to find and fix the rubbish in the text. "Smartness" comes with a price, it limits different use cases, like the one you discovered.
Maybe it's worth to assemble the encoding+cleaning+style operations separately? You can easily achieve these operations on strings using other specific libraries from npm. Then you could bypass spaces being added after full stops. What do you think?

**Comment by maxlapides** [comment]
Honestly I'm not sure what you mean exactly. I want to have a generic process for encoding and cleaning input strings, which is Detergent's aim. My problem is that this automatic space after period thing is causing more trouble than the value it's providing.

**Comment by revelt** [comment]
Let me have a think about it.

**Comment by revelt** [comment]
By the way, the new version 2.26.0 allows to turn off the addition of missing spaces after full stop, comma or semicolon.
